# Site settings
title: Zoe Genevieve LeBlanc
email: zgleblanc@gmail.com
description: > # Zoe LeBlanc's thoughts and scribbles.
url: "https://zoeleblanc.github.io" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-asterisk']
  Archives: ['Archives', '/archives', 'fa-archive']
  CV : ['CV', '/cv', 'fa-graduation-cap']
  Twitter : ['Twitter', 'https://twitter.com/Zoe_LeBlanc', 'fa-twitter']
  Instagram : ['Instagram', 'http://instagram.com/zoe_genevieve/', 'fa-instagram']
  Github : ['Github', 'https://github.com/ZoeLeBlanc/', 'fa-github']
  Linkedin : ['Linkedin', 'https://www.linkedin.com/pub/zoe-leblanc/46/650/70b', 'fa-linkedin-square']
  Contact : ['Contact', '/contact', 'fa-envelope']
single_footer: '<p>Zoe LeBlanc &copy; 2015 | built with Nutella <a href="/">latest posts</a></p>'
footer_links:
    Home: ['Home', '/']
    About: ['About', '/about']
    Archives: ['Archives', '/archives']
    Twitter: ['Twitter', 'https://twitter.com/Zoe_LeBlanc']
    Instagram: ['Instagram', 'http://instagram.com/zoe_genevieve/']


# Build settings
markdown: kramdown
