# Site settings
title: Zoe Genevieve LeBlanc
email: zgleblanc@gmail.com
description: > # Zoe LeBlanc's thoughts and scribbles.
url: "https://zoeleblanc.github.io" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/author/zoe', 'fa-asterisk']
  Archives: ['Archives', '/archives', 'fa-archive']
  Research: ['Research', '/research', 'fa-book']
  Teaching: ['Teaching', '/teaching', 'fa-paper-plane']
  Portfolio: ['Portfolio', 'https://zoeleblanc.github.io/portfolio', 'fa-folder']
  Twitter : ['Twitter', 'https://twitter.com/Zoe_LeBlanc', 'fa-twitter']
  Github : ['Github', 'https://github.com/ZoeLeBlanc/', 'fa-github']
  Tumblr : ['Tumblr', 'http://zoegenevieve.tumblr.com', 'fa-tumblr']
  Contact : ['Contact', '/contact', 'fa-envelope']
single_footer: '<p>Zoe LeBlanc &copy; 2015 | built with Jekyll and Nutella <a href="/">latest posts</a></p>'
footer_links:
    Home: ['Home', '/']
    About: ['About', '/author/zoe']
    Archives: ['Archives', '/archives']
    Twitter: ['Twitter', 'https://twitter.com/Zoe_LeBlanc']
twitter:
  consumer_key: 4MiOwZo9OiU4ufy4ZjpTQ
  consumer_secret: UlRmvLLqxGtK2CZfLsxFAUoSDeW9eRR2eN3QhKXBQ
  access_token: 840043015-7os6HSaUtcvDJ67gMZXEBAYxoDBk09tspynl6zJI
  access_token_secret: 4FiqpPuNXxMABEc3dDusKb2cND0pvfa3oxruuqjKs
instagram:
  instagram_cache: true
  instagram_cache_dir: '.instagram-cache'

# Build settings
markdown: kramdown
