# Site settings
title: Zoe Genevieve LeBlanc
email: zgleblanc@gmail.com
description: > # Zoe LeBlanc's thoughts and scribbles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zoeleblanc.github.io" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-asterisk']
  CV : ['CV', '/cv', 'fa-graduation-cap']
  Twitter : ['Twitter', 'https://twitter.com/Zoe_LeBlanc', 'fa-twitter']
  Github : ['Github', '/about', 'fa-github']
  Contact : ['Contact', '/contact', 'fa-envelope']
single_footer: '<p>Zoe LeBlanc &copy; 2015 | built with Nutella <a href="/">latest posts</a></p>'
footer_links:
    Home: ['Home', '/']
    About: ['About', '/about']
    Twitter: ['Twitter', 'https://twitter.com/Zoe_LeBlanc']


# Build settings
markdown: kramdown
